export enum ICON {
    typescript = "simple-icons:typescript",
    angular = "simple-icons:angular",
    react = "simple-icons:react",
    html = "ri:html5-fill",
    css = "simple-icons:css",
    javascript = "simple-icons:javascript",
    bootstrap = "simple-icons:bootstrap",
    primeng = "simple-icons:primeng",
    java = "ri:java-fill",
    springBoot = "simple-icons:spring",
    php = "simple-icons:php",
    laravel = "simple-icons:laravel",
    postgresql = "simple-icons:postgresql",
    mysql = "fontisto:mysql",
    github = "simple-icons:github",
    cypress = "simple-icons:cypress",
    jest = "simple-icons:jest",
    vitest = "simple-icons:vitest",
    git = "simple-icons:git",
    linux = "simple-icons:linux",
}